### ISSUE TITLE
Add pyyaml to installation instructions 

### ISSUE THREAD

**Issue by PatWalters** [isayevlab/Auto3D_pkg#21]
It doesn't look like the installation instructions include pyyaml

pip install pyyaml

**Comment by LiuCMU** [comment]
Hey, thanks for the feedback :) 

Auto3D doesn't use or import pyyaml in its modules. We tried to keep the dependencies as few as possible. Could you let me know why you think pyyaml should be installed?

**Comment by DrHermit** [comment]
Hi, I think it's because the auto3D.py program imports yaml and it would not run without pyyaml. I ran into the same issue when trying to run auto3D

**Comment by PatWalters** [comment]
Yes, exactly
________________________________

**Comment by LiuCMU** [comment]
I see, I will include pyyaml as the installation process in the future update. 

pyyaml is part of my Python environment since I used Anaconda to manage Python packages. I believe it automatically installs dependencies like pyyaml. Out of curiosity, could you let me know how you set up the Python environment?

**Comment by PatWalters** [comment]
I'm running conda and pyyaml is not installed by default.  Try this:

conda create --name test python=3.7
conda activate test
python -c 'import yaml'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'yaml'

pip install pyyaml
python -c 'import yaml'

**Comment by LiuCMU** [comment]
Got it, thanks!

**Comment by PatWalters** [comment]
I think you can just add pyyaml to the dependencies in your installation.yml

**Comment by LiuCMU** [comment]
Hey, this issue is solved. I'm closing it for now. Feel free to open new issues if you have any questions. 
Thanks for supporting Auto3D!
