### ISSUE TITLE
run comand not work  "python .\auto3d.py --path="data/smiles.sdf" --use_gpu=False"

### ISSUE THREAD

**Issue by lonngxiang** [isayevlab/Auto3D_pkg#32]
![image](https://user-images.githubusercontent.com/40717349/215259935-ab062a92-38ba-4f95-bf40-04cc069bab29.png)

**Comment by LiuCMU** [comment]
Looks like it's due to the path difference between different systems. For windows, the path should be `--path="data\smiles.sdf"`
