### ISSUE TITLE
How to generate multiple conformers?

### ISSUE THREAD

**Issue by dkoes** [isayevlab/Auto3D_pkg#35]
**Describe the bug**
I have tried setting `--k 25` and `--max_confs 25` and I still only get a single conformer per a smile.

**To Reproduce**
`~/git/Auto3D_pkg/auto3D.py rdrefined.smi --k 25 --max_confs `

rdrefined.smi contains all the smiles from PDBbind2020 refined set.
[rdrefined.smi.gz](https://github.com/isayevlab/Auto3D_pkg/files/10839942/rdrefined.smi.gz)

**Expected behavior**
More than one conformer per smile.

**System information:**
 - Operating System: Ubuntu 22.04
- Auto3D version: b76f112ea8ffe02cc49d82e081dc3c4dce0886a9
- Python version: 3.10.6
- RDKit version: 2022.09.4
- PyTorch version: 1.13.0+cu117

**Additional context**

**Comment by dkoes** [comment]
This problem is because the SMILES names have a period in them.  The period is there because you wouldn't let me have an underscore.  I recommend using a regular expression to extract the conformer id and let the name be whatever (including containing spaces, underscores, and periods).

**Comment by LiuCMU** [comment]
Hi David, thanks for the comment and detailed feedback!

That's indeed something we need to improve. 

For now, there is a utility function called `replace_` to help to replace the underscores in SMILES names:
```
from Auto3D.utils import replace_


names = ['smi_1', 'smi-2', 'smi3']
new_names = [replace_(name) for name in names]
print(new_names)  # output: ['smi-1', 'smi-2', 'smi3']
```

**Comment by LiuCMU** [comment]
Hello @dkoes , just an update that I updated auto3d and it accepts any names now. Please let us know in case any additional issues. For now, I will close this issue. Thanks!
