### ISSUE TITLE
Prune multiple conformers with a rmsd cutoff

### ISSUE THREAD

**Issue by ichxw** [isayevlab/Auto3D_pkg#39]
Does it support pruning conformers unless their RMSD is higher than a cutoff in rmsd?

**Comment by LiuCMU** [comment]
yeap. You can use this argument `threshold`. If the RMSD between two conformers are within the threhold, they are considered as duplicates. One of them will be removed. Duplicate removing are excuted after conformer enumeration and geometry optimization. The default value is 0.3 Angstrom.

This is also specified [here](https://github.com/isayevlab/Auto3D_pkg#parameters-in-auto3d)

**Comment by LiuCMU** [comment]
Sure, I will close this issue. Let us know if you have any other questions in the future!
