### ISSUE TITLE
Auto3D on Google Colab

### ISSUE THREAD

**Issue by Jameel9** [isayevlab/Auto3D_pkg#50]
I tried to run Auto3D on Colab (with GPU) but it return nothing and I couldn't find where was the problem.
It gives me a log file that reads

             _              _             _____   ____  
            / \     _   _  | |_    ___   |___ /  |  _ \ 
           / _ \   | | | | | __|  / _ \    |_ \  | | | |
          / ___ \  | |_| | | |_  | (_) |  ___) | | |_| |
         /_/   \_\  \__,_|  \__|  \___/  |____/  |____/  2.1.0
                // Automatic generation of the low-energy 3D structures                                      
        
================================================================================
                               INPUT PARAMETERS
================================================================================
path: ligands/smiles.smi
k: 1
window: False
verbose: False
job_name: 20230917-083135-620261
enumerate_tautomer: False
tauto_engine: rdkit
pKaNorm: True
isomer_engine: rdkit
enumerate_isomer: True
mode_oe: classic
mpi_np: 4
max_confs: None
use_gpu: True
capacity: 42
gpu_idx: 0
optimizing_engine: AIMNET
patience: 1000
opt_steps: 5000
convergence_threshold: 0.003
threshold: 0.3
memory: None
batchsize_atoms: 1024
input_format: smi
================================================================================
                               RUNNING PROCESS
================================================================================
Checking input file...
'''
             _              _             _____   ____  
            / \     _   _  | |_    ___   |___ /  |  _ \ 
           / _ \   | | | | | __|  / _ \    |_ \  | | | |
          / ___ \  | |_| | | |_  | (_) |  ___) | | |_| |
         /_/   \_\  \__,_|  \__|  \___/  |____/  |____/  2.1.0
                // Automatic generation of the low-energy 3D structures                                      
        
================================================================================
                               INPUT PARAMETERS
================================================================================
path: ligands/smiles.smi
k: 1
window: False
verbose: False
job_name: 20230917-083138-867542
enumerate_tautomer: False
tauto_engine: rdkit
pKaNorm: True
isomer_engine: rdkit
enumerate_isomer: True
mode_oe: classic
mpi_np: 4
max_confs: None
use_gpu: True
capacity: 42
gpu_idx: 0
optimizing_engine: AIMNET
patience: 1000
opt_steps: 5000
convergence_threshold: 0.003
threshold: 0.3
memory: None
batchsize_atoms: 1024
input_format: smi
================================================================================
                               RUNNING PROCESS
================================================================================
Checking input file...

-----------------------------------

and the cell finishes running after few seconds as everything was completed as normal. 
I could not find any _3d.sdf file in the working directory.

**Comment by LiuCMU** [comment]
Hello @Jameel9, was this issue sovled?

If not, could you attach the log file and the cell output so that I could look into this issue? Thanks!

**Comment by Jameel9** [comment]
Yes. It worked when I add a name for each smiles string. 

Thank you for willing to help.

**Comment by LiuCMU** [comment]
Cool! Please let us know if you have feedback in the future. 

We are planning several updates to Auto3D, too, stay tuned :)
