### ISSUE TITLE
issues when running from the CLI if username contains '.' (dot)

### ISSUE THREAD

**Issue by dealmeida-h** [isayevlab/Auto3D_pkg#51]
**Describe the bug**
Running auto3d from the CLI throws an error if the username has a dot. 
**To Reproduce**
1. create a new user test.user
2. run python auto3d.py "example/files/smiles.smi" --k=1 --optimizing_engine="ANI2x"
3. See error: `PermissionError: [Errno 13] Permission denied: '/Users/test_reduced.smi'`

**Expected behavior**
Auto3D would run and generate 1st lowest energy conformer

**Screenshots**

**System information:**
 - Operating System: MacOS
- Auto3D version: latest
- Python version:
- RDKit version:
- PyTorch version:

**Additional context**
Problem comes from how you're defining the smiles_reduced variable (line 50 from auto3d.py):
`smiles_reduced = smiles_enumerated.split('.')[0] + '_reduced.smi'`
the split is splitting the entire path, taking the first item (the first part of the username in this setting) and attaching the _reduced.smi. You could solve the issue by splitting on `'enumerated.'` instead of `'.'`. But even if this is solved in this line, line 45 also suffers from the same problem (gives the following error : `'OSError: File error: Bad output file /Users/test0.sdf'`).

**Comment by LiuCMU** [comment]
Hey @dealmeida-h , this bug should have been fixed in the latest version of auto3d. Please let us know if there is additional issues.
