### ISSUE TITLE
Typo in output

### ISSUE THREAD

**Issue by OlgaGKononova** [isayevlab/Auto3D_pkg#53]
Hi there. Little typo in the output print-out: "select"

```
Optimization finished at step 2343:   Total 3D structures: 2290  Converged: 2245   Dropped(Oscillating): 45    Active: 0
Begin to slelect structures that satisfy the requirements...
Energy unit: Hartree if implicit.
```

**Comment by LiuCMU** [comment]
nice catch! We will fix it, thank you!

**Comment by LiuCMU** [comment]
We have fixed this as well as a few other typos. The new documentation is available at https://auto3d.readthedocs.io/en/latest/. 

Please let us know if you have any suggestions. Thanks!
