### ISSUE TITLE
SMD solvation energy

### ISSUE THREAD

**Issue by xiaolinpan** [isayevlab/Auto3D_pkg#64]
Thank you for your open-source code. I have a question about AIMNet model. Are SMD solvation energies included in the model?

**Comment by LiuCMU** [comment]
Hello, SMD solvation energies are not included in the current AIMNet model unfortunately. For more info about this AIMNet model, please check out this preprint: https://chemrxiv.org/engage/chemrxiv/article-details/6525b39e8bab5d2055123f75

Please let us if you have additional questions.

**Comment by xiaolinpan** [comment]
Thank you very much.
