### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by xiaolinpan** [isayevlab/Auto3D_pkg#73]
I am writing to express my appreciation for your open-source project. It is a valuable tool for the field of drug discovery. I am interested in retraining a model using the dataset you generated in your paper. Could you please advise me on how to access the dataset for download? Thank you for your time and consideration.

**Comment by LiuCMU** [comment]
Thanks for the encouraging words! Which dataset are you referring to?

**Comment by xiaolinpan** [comment]
Which is generated for ANI-2xt training.

**Comment by LiuCMU** [comment]
Unfortunately, that dataset was not published. A similar dataset is ANI-1, which is public: https://www.nature.com/articles/sdata2017193

**Comment by xiaolinpan** [comment]
Thanks a lot.
