### ISSUE TITLE
Tag and Release GitHub package?

### ISSUE THREAD

**Issue by ghutchis** [isayevlab/Auto3D_pkg#82]
If there's a new 2.3.0 release on PyPI, can someone please create a release tag on GitHub? This is important for packaging (conda-forge, for example cannot find the new release).

It's also useful since the current release listed https://github.com/isayevlab/Auto3D_pkg/releases is 2.2.7.

**Comment by LiuCMU** [comment]
Hi, I already made a tag for 2.3.0. Please let me know if there is anything I can help with. Thanks!
